#%RAML 1.0
title: MusicHubAPI
version: v1
protocols: [ HTTP ]
mediaType: application/json
types: 
  User: !include User.raml
  Artist: !include Artist.raml
  Album: !include Album.raml

/users/register:
    post:
        description: "Registers a user to the API and creates a MongoDB instance."
        responses: 
            201:
                body:
                    application/json:
                        example: |
                            {
                                "user": "64a49eb22db3bbcbc96b6d04"
                            }
            409:
                body:
                    application/json:
                        example: |
                        {
                            "errors": {
                                "email": "that email is already registered",
                                "password": ""
                            }
                        },
                        {
                            "errors": {
                                "email": "",
                                "password": "Sorry your password isn't long enough"
                            }
                        }

/users/login:
    post:
        description: Logins a user to the API and creates a JWT.
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YTQ5ZWIyMmRiM2JiY2JjOTZiNmQwNCIsImlhdCI6MTY4ODUxMDM4NSwiZXhwIjoxNjg5MTE1MTg1fQ.Kk2-Fsp4VPPgsWuliLyzbjkHZKkO7inM1AnJJACeTyQ"
                            }
            401:
                body:
                    application/json:
                        example: |
                            {
                                "errors": {
                                    "email": "",
                                    "password": "That password is incorrect"
                                }
                            }

/users/logout:
    post:
        description: Logs a user out.
        responses:
            200:
                {
                    "message": "You have been logged out."
                }

/artists:
    get:
        description: Gets all artists. 
        responses:
            200:
                body:
                    application/json:
                        {
                            "artists": [
                                {
                                    "_id": 120398123810bafsda123,
                                    "artistName": "Foo Fighters",
                                    "location": "Seattle",
                                    "artistFormed": 1994,
                                    "active": "Yes",
                                    "artistBio": "Foo Fighters were formed in 1994 in Seattle, United States"
                                }
                            ]
                        }
                        
            403:
                body:
                    application/json:
                        {
                            "error": "You are not authenticated."
                        }

            404:
                body:
                    application/json:
                        {
                            "error": "No artists found."
                        }

/artists/{id}:
    get:
        description: Gets a artist based upon id. 
        responses:
            200:
                body:
                    application/json:
                        {
                            "artist": 
                                {
                                    "_id": 120398123810bafsda123,
                                    "artistName": "Foo Fighters",
                                    "location": "Seattle",
                                    "artistFormed": 1994,
                                    "active": "Yes",
                                    "artistBio": "Foo Fighters were formed in 1994 in Seattle, United States"
                                }
                        }

            403:
                body:
                    application/json:
                        {
                            "error": "You are not authenticated."
                        }

            404:
                body:
                    application/json:
                        {
                            "error": "Could not find that artist."
                        }

/albums:
    get:
        description: Gets all albums. 
        responses:
            200:
                body:
                    application/json:
                        {
                            "albums": [
                                {
                                    "_id": "64a3ede5985b27282229660b",
                                    "albumName": "Suicide",
                                    "albumArtist": "Suicide",
                                    "tracks": 7,
                                    "releaseYear": 1977,
                                    "genre": "Rock",
                                    "__v": 0
                                }
                            ]
                        }
                        
            403:
                body:
                    application/json:
                        {
                            "error": "You are not authenticated."
                        }

            404:
                body:
                    application/json:
                        {
                            "error": "No albums found."
                        }

/albums/{id}:
    get:
        description: Gets an album based upon id. 
        responses:
            200:
                body:
                    application/json:
                        {
                            "album": {
                                "_id": "64a3ede5985b27282229660b",
                                "albumName": "Suicide",
                                "albumArtist": "Suicide",
                                "tracks": 7,
                                "releaseYear": 1977,
                                "genre": "Rock",
                                "__v": 0
                            }
                        }

            403:
                body:
                    application/json:
                        {
                            "error": "You are not authenticated."
                        }

            404:
                body:
                    application/json:
                        {
                            "error": "Could not find that album."
                        }

/search/{id}:
    get:
        description: Show search results
        responses:
            200:
                body:
                    application/json:
                        example:
                            {
                                "results": [
                                    [
                                        {
                                            "_id": "64a3ede5985b27282229660b",
                                            "albumName": "Suicide",
                                            "albumArtist": "Suicide",
                                            "tracks": 7,
                                            "releaseYear": 1977,
                                            "genre": "Rock",
                                            "__v": 0
                                        }
                                    ]
                                ]
                            }
            403:
                body:
                    application/json:
                        example:
                            {
                                "error": "You are not authenticated"
                            }

            404:
                body:
                    application/json:
                        example:
                            {
                                "error": "No data was found based on your search criteria."
                            }

/artists/add:
    post:
        description: Adds an Artist
        responses:
            201:
                body:
                    application/json:
                        example:
                            {
                                "artist": "Successfully created 120398123810bafsda123"
                            }
            403:
                body:
                    application/json:
                        example:
                            {
                                "error": "You are not authenticated."
                            }
            409:
                body:
                    application/json:
                        example:
                            {
                                "error": "Data not inputted correctly."
                            }



/albums/add:
    post:
        description: Adds an Album
        responses:
            201:
                body:
                    application/json:
                        example:
                            {
                                "album": "Successfully created bva98123810bafsda123"
                            }
            403:
                body:
                    application/json:
                        example:
                            {
                                "error": "You are not authenticated."
                            }
            409:
                body:
                    application/json:
                        example:
                            {
                                "error": "Data not inputted correctly."
                            }

/albums/genre/{genre}:
    get:
        description: Gets albums based on Genre.
        responses:
            200:
                body:
                    application/json:
                        example:
                            {
                                "results": [
                                    [
                                        {
                                            "_id": "64a3ede5985b27282229660b",
                                            "albumName": "Suicide",
                                            "albumArtist": "Suicide",
                                            "tracks": 7,
                                            "releaseYear": 1977,
                                            "genre": "Rock",
                                            "__v": 0
                                        }
                                    ]
                                ]
                            }

            403:
                body:
                    applicaition/json:
                        example:
                            {
                                "error": "You are not authenticated."
                            }
            404:
                body:
                    application/json:
                        example:
                            {
                                "error": "Data not found."
                            }

/albums/update/{id}:
    patch:
        description: Updates an album based upon a given ID
        responses:
            202:
                body:
                    application/json:
                        example:
                            {
                                "message": "123089ba123 has been updated."
                            }
            403: 
                body:
                    applicaiton/json:
                        example:
                            {
                                "error": "You are not authenticated."
                            }
            404:
                body:
                    application/json:
                        example:
                            {
                                "error": "123089ba123 could not be found in the database."
                            }

/artist/update/{id}:
    patch:
        description: Updates an artist based upon a given ID
        responses:
            202:
                body:
                    application/json:
                        example:
                            {
                                "message": "123089ba123 has been updated."
                            }
            403: 
                body:
                    applicaiton/json:
                        example:
                            {
                                "error": "You are not authenticated."
                            }
            404:
                body:
                    application/json:
                        example:
                            {
                                "error": "123089ba123 could not be found in the database."
                            }

/artists/delete/{id}:
    delete:
        description: Deletes an artist based upon an id
        responses:
        202:
            body:
                application/json:
                    example:
                        {
                            "message": "1239890basdf123 has been deleted."
                        }
        403:
            body:
                applicaiton/json:
                    example:
                        {
                            "error": "You are not authenticated."
                        }

        404:
            body:
                application/json:
                    example:
                        {
                            "error": "1239890basdf123 could not be found in the database."
                        }

/albums/delete/{id}:
    delete:
        description: Deletes an album based upon an id
        responses:
        202:
            body:
                application/json:
                    example:
                        {
                            "message": "1239890basdf123 has been updated."
                        }
        403:
            body:
                applicaiton/json:
                    example:
                        {
                            "error": "You are not authenticated."
                        }

        404:
            body:
                application/json:
                    example:
                        {
                            "error": "1239890basdf123 could not be found in the database."
                        }